var Gegenteil_JSON = {
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Peritrop\u00E8" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Sitt" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Adynamie" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Einfachheit" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Radverkehrsanlage" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Anton_(Name)" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://de.wikipedia.org/wiki/Gegenteil" : { "http://xmlns.com/foaf/0.1/primaryTopic" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Liste_von_Links-Rechts-Gegens\u00E4tzen" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Negation" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegensatz" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Komplement_(Mengenlehre)" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Umgangssprache" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Antonym" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Kategorie:Abstraktum" } ,
      { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Sprachwissenschaft" } ] ,
    "http://www.w3.org/2002/07/owl#sameAs" : [ { "type" : "uri", "value" : "http://de.dbpedia.org/resource/Gegenteil" } ,
      { "type" : "uri", "value" : "http://wikidata.dbpedia.org/resource/Q1498321" } ,
      { "type" : "uri", "value" : "http://wikidata.org/entity/Q1498321" } ] ,
    "http://dbpedia.org/ontology/abstract" : [ { "type" : "literal", "value" : "Das Gegenteil einer Sache oder einer Eigenschaft ist umgangssprachlich meistens eine Sache oder eine Eigenschaft, die von der erstgenannten eine Art Spiegelung eines gedachten Mittelpunktes darstellt.So w\u00E4re also umgangssprachlich das Gegenteil von gro\u00DF klein, weil gro\u00DF und klein gef\u00FChlt gleich weit weg sind vom gedachten Mittelpunkt \u201Enormalgro\u00DF\u201C. Das Gegenteil von winzig w\u00E4re allerdings riesig, da der gef\u00FChlte Abstand von winzig zu normalgro\u00DF als gr\u00F6\u00DFer empfunden wird, als dies bei dem einfachen \u201Eklein\u201C der Fall w\u00E4re.In der Sprachwissenschaft ist mit Gegenteil ein Gegenbegriff oder Gegenwort gemeint, das als Antonym bezeichnet wird. Es werden verschiedene Arten von Antonymien unterschieden. Antonym = Gegenteil. (Das Antonym von Synonym ist Antonym.)Mathematisch gesehen ist das Gegenteil einer Menge die komplement\u00E4re Menge bzw. das Gegenteil einer Aussage die negierte Aussage.In der Philosophie unterscheidet man seit Aristoteles vier Arten von Gegenteilen bzw. des logischen Gegensatzes: den kontradiktorischen (z. B. wei\u00DF \u2013 nicht wei\u00DF) den kontr\u00E4ren (z. B. wei\u00DF \u2013 schwarz) den privativen (z. B. sehend \u2013 blind) den relativen (z. B. doppelt \u2013 halb)" , "lang" : "de" } ] ,
    "http://purl.org/dc/terms/subject" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Kategorie:Abstraktum" } ] ,
    "http://www.w3.org/2000/01/rdf-schema#label" : [ { "type" : "literal", "value" : "Gegenteil" , "lang" : "de" } ] ,
    "http://www.w3.org/2000/01/rdf-schema#comment" : [ { "type" : "literal", "value" : "Das Gegenteil einer Sache oder einer Eigenschaft ist umgangssprachlich meistens eine Sache oder eine Eigenschaft, die von der erstgenannten eine Art Spiegelung eines gedachten Mittelpunktes darstellt.So w\u00E4re also umgangssprachlich das Gegenteil von gro\u00DF klein, weil gro\u00DF und klein gef\u00FChlt gleich weit weg sind vom gedachten Mittelpunkt \u201Enormalgro\u00DF\u201C." , "lang" : "de" } ] ,
    "http://xmlns.com/foaf/0.1/isPrimaryTopicOf" : [ { "type" : "uri", "value" : "http://de.wikipedia.org/wiki/Gegenteil" } ] ,
    "http://dbpedia.org/ontology/wikiPageRevisionID" : [ { "type" : "literal", "value" : 127829481 , "datatype" : "http://www.w3.org/2001/XMLSchema#integer" } ] ,
    "http://www.w3.org/ns/prov#wasDerivedFrom" : [ { "type" : "uri", "value" : "http://de.wikipedia.org/wiki/Gegenteil?oldid=127829481" } ] ,
    "http://dbpedia.org/ontology/wikiPageLength" : [ { "type" : "literal", "value" : 1533 , "datatype" : "http://www.w3.org/2001/XMLSchema#integer" } ] ,
    "http://dbpedia.org/ontology/wikiPageOutDegree" : [ { "type" : "literal", "value" : 9 , "datatype" : "http://www.w3.org/2001/XMLSchema#integer" } ] ,
    "http://dbpedia.org/ontology/wikiPageID" : [ { "type" : "literal", "value" : 171679 , "datatype" : "http://www.w3.org/2001/XMLSchema#integer" } ] ,
    "http://dbpedia.org/ontology/wikiPageExternalLink" : [ { "type" : "uri", "value" : "http://was-ist-das-gegenteil-von.de/" } ] ,
    "http://dbpedia.imp.fu-berlin.de:49156/property/wikiPageUsesTemplate" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Vorlage:Wiktionary" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Wachstum_(Mathematik)" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Palinodie" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Kryptographie" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/1984_(Roman)" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Unendlichkeit" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Omote" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] } ,
  "http://dbpedia.imp.fu-berlin.de:49156/resource/Kontraktion_(Physik)" : { "http://dbpedia.org/ontology/wikiPageWikiLink" : [ { "type" : "uri", "value" : "http://dbpedia.imp.fu-berlin.de:49156/resource/Gegenteil" } ] }
};